/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import connection.ConexaoSQLite;
import dao.GestorRecursosDao;
import dao.ReuniaoDao;
import dao.SalaDao;
import dao.UsuarioDao;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.GestorRecursos;
import model.Reuniao;
import model.Sala;
import model.Usuario;
import model.UsuarioComum;

/**
 *
 * @author Paulo
 */
public class TelaCadastReuniao extends javax.swing.JInternalFrame {

    /**
     * Creates new form TelaCastReuniao
     */
    public TelaCadastReuniao() {
        initComponents();
        alimentarTabela();
        alimentarListSala();
    }
    
    Usuario u;
    String cpfUsuarioAtual;
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        taDescAta = new javax.swing.JTextArea();
        btnCriarReuniao = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        tbUsuarios = new javax.swing.JTable();
        jScrollPane5 = new javax.swing.JScrollPane();
        tbParticipantes = new javax.swing.JTable();
        btnAdicionarPart = new javax.swing.JButton();
        btnRemover = new javax.swing.JButton();
        cbDia = new javax.swing.JComboBox<>();
        cbMes = new javax.swing.JComboBox<>();
        ftfAno = new javax.swing.JFormattedTextField();
        cbHoraI = new javax.swing.JComboBox<>();
        cbMinI = new javax.swing.JComboBox<>();
        cbHoraF = new javax.swing.JComboBox<>();
        cbMinF = new javax.swing.JComboBox<>();
        cbListSala = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        lblSala = new javax.swing.JLabel();

        setClosable(true);
        setTitle("Cadastro de Reuniões");

        jPanel1.setBackground(new java.awt.Color(0, 113, 146));

        jLabel1.setFont(new java.awt.Font("Serif", 0, 36)); // NOI18N
        jLabel1.setText("Criar Reunião");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(407, 407, 407))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(42, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(230, 240, 240));

        jLabel2.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jLabel2.setText("Data");

        jLabel3.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jLabel3.setText("Hora Inicio");

        jLabel4.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jLabel4.setText("Hora Fim");

        jLabel5.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jLabel5.setText("Descrição Ata");

        taDescAta.setColumns(20);
        taDescAta.setRows(5);
        jScrollPane1.setViewportView(taDescAta);

        btnCriarReuniao.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnCriarReuniao.setText("Criar Reunião");
        btnCriarReuniao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCriarReuniaoActionPerformed(evt);
            }
        });

        tbUsuarios.setFont(new java.awt.Font("Serif", 0, 11)); // NOI18N
        tbUsuarios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Usuario", "Cpf", "Email"
            }
        ));
        jScrollPane4.setViewportView(tbUsuarios);

        tbParticipantes.setFont(new java.awt.Font("Serif", 0, 11)); // NOI18N
        tbParticipantes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Participantes", "Cpf", "Email"
            }
        ));
        jScrollPane5.setViewportView(tbParticipantes);

        btnAdicionarPart.setText("Adicionar >>");
        btnAdicionarPart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdicionarPartActionPerformed(evt);
            }
        });

        btnRemover.setText("<< Remover");
        btnRemover.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemoverActionPerformed(evt);
            }
        });

        cbDia.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Dia", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));
        cbDia.setToolTipText("");

        cbMes.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Mês", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12" }));
        cbMes.setToolTipText("");

        try {
            ftfAno.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        ftfAno.setToolTipText("Ano");

        cbHoraI.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Hora", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20" }));

        cbMinI.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Min", "00", "10", "15", "20", "25", "30", "35", "40", "45", "50", "55", " ", " " }));

        cbHoraF.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Hora", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20" }));

        cbMinF.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Min", "00", "10", "15", "20", "25", "30", "35", "40", "45", "50", "55", " ", " " }));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jScrollPane1)
                        .addGap(689, 689, 689))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(cbDia, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(cbMes, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(ftfAno, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cbHoraF, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cbHoraI, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(cbMinI, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cbMinF, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jLabel5))
                        .addGap(18, 18, Short.MAX_VALUE)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnAdicionarPart)
                            .addComponent(btnRemover))
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 299, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(100, 100, 100))))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(429, 429, 429)
                .addComponent(btnCriarReuniao, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(cbDia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbMes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ftfAno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel3)
                                    .addComponent(cbHoraI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel4)
                                    .addComponent(cbHoraF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(cbMinI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(cbMinF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(80, 80, 80)
                        .addComponent(jLabel5))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(17, 17, 17)
                                .addComponent(btnAdicionarPart)
                                .addGap(26, 26, 26)
                                .addComponent(btnRemover))
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addComponent(btnCriarReuniao, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(36, Short.MAX_VALUE))
        );

        cbListSala.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbListSalaActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        jLabel6.setText("Sala selecionada =");

        jLabel7.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jLabel7.setText("Salas");

        lblSala.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        lblSala.setText("  ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(630, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addComponent(jLabel6)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblSala)
                            .addGap(138, 138, 138))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addComponent(cbListSala, javax.swing.GroupLayout.PREFERRED_SIZE, 301, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(91, 91, 91)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addGap(229, 229, 229))))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 6, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 1016, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(351, Short.MAX_VALUE)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cbListSala, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(lblSala))
                .addGap(212, 212, 212))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, 0)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCriarReuniaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCriarReuniaoActionPerformed
          
        
        ConexaoSQLite cSql = new ConexaoSQLite();
        GestorRecursosDao grDao = new GestorRecursosDao(cSql);
        ReuniaoDao rDao = new ReuniaoDao(cSql);
        DefaultTableModel tbP = (DefaultTableModel) tbParticipantes.getModel();
        
        if(cbDia.getSelectedItem().toString() != "Dia" && cbMes.getSelectedItem().toString() != "Mês" && 
                cbHoraF.getSelectedItem().toString() != "Hora" && cbHoraI.getSelectedItem().toString() != "Hora" &&
                cbMinF.getSelectedItem().toString() != "Min" && cbMinI.getSelectedItem().toString() != "Min"){
            
            Reuniao r = new Reuniao();
            r.setDescricao(taDescAta.getText());
            r.setDataReuniao(cbDia.getSelectedItem().toString() + "/" +cbMes.getSelectedItem().toString());
            r.setHorarioFim(cbHoraF.getSelectedItem().toString()+":"+cbMinF.getSelectedItem().toString());
            r.setHorarioInicio(cbHoraI.getSelectedItem().toString()+":"+cbMinI.getSelectedItem().toString());
            r.setLocal(lblSala.getText());
            
            
            UsuarioDao uD = new UsuarioDao(cSql);
            cSql.conectar();
            System.out.println(tbParticipantes.getRowCount());
            for(int i = 0; i == tbParticipantes.getRowCount(); i++){
                u = new UsuarioComum();
                u.setNome(tbParticipantes.getValueAt(i, 1).toString());
                r.setParticipantes((UsuarioComum) u);
                System.out.println(u);
                System.out.println(r);
                System.out.println("Oi");
            }
            r.setProprietario(uD.pegarUsuario(cpfUsuarioAtual));
            grDao.inserirGestorRecurso(r);
            cSql.conectar();
            //rDao.inserirReuniao(r);
            JOptionPane.showMessageDialog(null, "Reunião Criada");
            
            
        }else{
            JOptionPane.showMessageDialog(null, "Preencha todos os campos");
        }
        
    }//GEN-LAST:event_btnCriarReuniaoActionPerformed

    private void btnAdicionarPartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdicionarPartActionPerformed

        DefaultTableModel tbP = (DefaultTableModel) tbParticipantes.getModel();

        int aux = 0;
        System.out.println(tbP.getRowCount());
        for (int i = 0; i < tbP.getRowCount(); i++) {

            if (tbParticipantes.getValueAt(i, 1) == tbUsuarios.getValueAt(tbUsuarios.getSelectedRow(), 1)) {
                aux++;
            }

        }

        if (aux == 0) {

            tbP.addRow(new Object[]{
                tbUsuarios.getValueAt(tbUsuarios.getSelectedRow(), 0),
                tbUsuarios.getValueAt(tbUsuarios.getSelectedRow(), 1),
                tbUsuarios.getValueAt(tbUsuarios.getSelectedRow(), 2)

            });
        }else{
            JOptionPane.showMessageDialog(null, "Esse paricipante já existe em sua lista");
        }
        System.out.println(tbP.getRowCount());
    }//GEN-LAST:event_btnAdicionarPartActionPerformed

    
     public void alimentarTabela() {

        DefaultTableModel tbU = (DefaultTableModel) tbUsuarios.getModel();
        tbU.setNumRows(0);
        ConexaoSQLite connection = new ConexaoSQLite();
        UsuarioDao uDao = new UsuarioDao(connection);

        for (Usuario u : uDao.listarTodosUsuarios()) {

            tbU.addRow(new Object[]{
                u.getId(),
                u.getNome(),
                u.getCpf(),
                u.getEmail()
            });

        }

    }
     
     public void alimentarListSala(){
         
         ConexaoSQLite connection = new ConexaoSQLite();
         SalaDao sDao = new SalaDao(connection);
         
         for (Sala salas : sDao.listarTodasSalas()) {
             
            cbListSala.addItem(salas.getNome());
             
         }
     }
     
     public void pegarUsuarioAtual(String usuarioAt){
         cpfUsuarioAtual = usuarioAt;
     }
    
    private void btnRemoverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemoverActionPerformed

        DefaultTableModel tbP = (DefaultTableModel) tbParticipantes.getModel();

        if (tbParticipantes.getSelectedRow() != -1) {
            tbP.removeRow(tbParticipantes.getSelectedRow());
        } else {

            JOptionPane.showMessageDialog(null, "Selecione a linha para ser removida");

        }

    }//GEN-LAST:event_btnRemoverActionPerformed

    private void cbListSalaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbListSalaActionPerformed
            
       lblSala.setText(cbListSala.getSelectedItem().toString()); 
        
    }//GEN-LAST:event_cbListSalaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdicionarPart;
    private javax.swing.JButton btnCriarReuniao;
    private javax.swing.JButton btnRemover;
    private javax.swing.JComboBox<String> cbDia;
    private javax.swing.JComboBox<String> cbHoraF;
    private javax.swing.JComboBox<String> cbHoraI;
    private javax.swing.JComboBox<Object> cbListSala;
    private javax.swing.JComboBox<String> cbMes;
    private javax.swing.JComboBox<String> cbMinF;
    private javax.swing.JComboBox<String> cbMinI;
    private javax.swing.JFormattedTextField ftfAno;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JLabel lblSala;
    private javax.swing.JTextArea taDescAta;
    private javax.swing.JTable tbParticipantes;
    private javax.swing.JTable tbUsuarios;
    // End of variables declaration//GEN-END:variables
}
