/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

/**
 *
 * @author Paulo
 */
public class TelaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form TelaPrincipal
     */
    public TelaPrincipal() {
        initComponents();
    }
    
    String cpfUsuarioAtual;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        dsktTelaP = new javax.swing.JDesktopPane();
        mbPrincipal = new javax.swing.JMenuBar();
        menuReuniao = new javax.swing.JMenu();
        miCadastReuniao = new javax.swing.JMenuItem();
        miReunioesConf = new javax.swing.JMenuItem();
        miNaoConf = new javax.swing.JMenuItem();
        miEditarAta = new javax.swing.JMenuItem();
        miSugerirSala = new javax.swing.JMenuItem();
        miBaixarAtas = new javax.swing.JMenuItem();
        menuSair = new javax.swing.JMenu();
        miLogoff = new javax.swing.JMenuItem();

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        dsktTelaP.setBackground(new java.awt.Color(230, 240, 240));
        dsktTelaP.setAutoscrolls(true);

        javax.swing.GroupLayout dsktTelaPLayout = new javax.swing.GroupLayout(dsktTelaP);
        dsktTelaP.setLayout(dsktTelaPLayout);
        dsktTelaPLayout.setHorizontalGroup(
            dsktTelaPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 540, Short.MAX_VALUE)
        );
        dsktTelaPLayout.setVerticalGroup(
            dsktTelaPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 353, Short.MAX_VALUE)
        );

        mbPrincipal.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        menuReuniao.setText("Reunião");

        miCadastReuniao.setText("Cadastrar Reunião");
        miCadastReuniao.setIconTextGap(5);
        miCadastReuniao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miCadastReuniaoActionPerformed(evt);
            }
        });
        menuReuniao.add(miCadastReuniao);

        miReunioesConf.setText("Listar Reuniões Confirmadas");
        miReunioesConf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miReunioesConfActionPerformed(evt);
            }
        });
        menuReuniao.add(miReunioesConf);

        miNaoConf.setText("Listar Reuniões não Confirmadas");
        miNaoConf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miNaoConfActionPerformed(evt);
            }
        });
        menuReuniao.add(miNaoConf);

        miEditarAta.setText("Editar Ata");
        miEditarAta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miEditarAtaActionPerformed(evt);
            }
        });
        menuReuniao.add(miEditarAta);

        miSugerirSala.setText("Sugerir sala");
        miSugerirSala.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miSugerirSalaActionPerformed(evt);
            }
        });
        menuReuniao.add(miSugerirSala);

        miBaixarAtas.setText("Baixar atas");
        miBaixarAtas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miBaixarAtasActionPerformed(evt);
            }
        });
        menuReuniao.add(miBaixarAtas);

        mbPrincipal.add(menuReuniao);

        menuSair.setText("Sair");

        miLogoff.setText("Logoff");
        miLogoff.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miLogoffActionPerformed(evt);
            }
        });
        menuSair.add(miLogoff);

        mbPrincipal.add(menuSair);

        setJMenuBar(mbPrincipal);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(dsktTelaP)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(dsktTelaP)
        );

        setSize(new java.awt.Dimension(556, 411));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void miCadastReuniaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miCadastReuniaoActionPerformed
        
        TelaCadastReuniao tlR = new TelaCadastReuniao();
        tlR.pegarUsuarioAtual(cpfUsuarioAtual);
        dsktTelaP.add(tlR);
        tlR.setVisible(true);

    }//GEN-LAST:event_miCadastReuniaoActionPerformed

    private void miLogoffActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miLogoffActionPerformed
        
        TelaInicial tl = new TelaInicial();
        tl.setVisible(true);
        this.dispose();
        
    }//GEN-LAST:event_miLogoffActionPerformed

    private void miEditarAtaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miEditarAtaActionPerformed
        
        TelaEditarAta eAta = new TelaEditarAta();
        dsktTelaP.add(eAta);
        eAta.setVisible(true);
        
    }//GEN-LAST:event_miEditarAtaActionPerformed

    private void miNaoConfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miNaoConfActionPerformed
                
        TelaDasReunioesGestor tRG = new TelaDasReunioesGestor();
        dsktTelaP.add(tRG);
        tRG.setVisible(true);
        
    }//GEN-LAST:event_miNaoConfActionPerformed

    private void miSugerirSalaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miSugerirSalaActionPerformed
        
        TelaCadastroSala tS = new TelaCadastroSala();
        dsktTelaP.add(tS);
        tS.setVisible(true);
        
    }//GEN-LAST:event_miSugerirSalaActionPerformed

    private void miReunioesConfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miReunioesConfActionPerformed
        
        TelaReunioesConf trC = new TelaReunioesConf();
        dsktTelaP.add(trC);
        trC.setVisible(true);
        
    }//GEN-LAST:event_miReunioesConfActionPerformed

    private void miBaixarAtasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miBaixarAtasActionPerformed
        TelaDownloadAta tDA = new TelaDownloadAta();
        dsktTelaP.add(tDA);
        tDA.setVisible(true);
    }//GEN-LAST:event_miBaixarAtasActionPerformed

    public void usuarioAtual(String cpfUsAtual){
        
        cpfUsuarioAtual = cpfUsAtual;
        
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane dsktTelaP;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JMenuBar mbPrincipal;
    private javax.swing.JMenu menuReuniao;
    private javax.swing.JMenu menuSair;
    private javax.swing.JMenuItem miBaixarAtas;
    private javax.swing.JMenuItem miCadastReuniao;
    private javax.swing.JMenuItem miEditarAta;
    private javax.swing.JMenuItem miLogoff;
    private javax.swing.JMenuItem miNaoConf;
    private javax.swing.JMenuItem miReunioesConf;
    private javax.swing.JMenuItem miSugerirSala;
    // End of variables declaration//GEN-END:variables
}
