/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import connection.ConexaoSQLite;
import dao.ReuniaoDao;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;
import model.Reuniao;
import util.GeradorTxt;

/**
 *
 * @author Paulo
 */
public class TelaDownloadAta extends javax.swing.JInternalFrame {

    /**
     * Creates new form TelaDownloadAta
     */
    public TelaDownloadAta() {
        initComponents();
        alimentarTabela();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tbReunioesAtaDownload = new javax.swing.JTable();
        btnDownload = new javax.swing.JButton();

        setClosable(true);
        setResizable(true);

        tbReunioesAtaDownload.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "id", "Descrição", "Data", "Hora Inicio", "Hora Fim", "Proprietario", "Sala"
            }
        ));
        tbReunioesAtaDownload.setUpdateSelectionOnSort(false);
        tbReunioesAtaDownload.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tbReunioesAtaDownloadFocusGained(evt);
            }
        });
        tbReunioesAtaDownload.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbReunioesAtaDownloadMouseClicked(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                tbReunioesAtaDownloadMouseReleased(evt);
            }
        });
        jScrollPane1.setViewportView(tbReunioesAtaDownload);

        btnDownload.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        btnDownload.setText("Download");
        btnDownload.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDownloadActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(255, 255, 255)
                .addComponent(btnDownload, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(264, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 649, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(359, Short.MAX_VALUE)
                .addComponent(btnDownload, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 316, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(116, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tbReunioesAtaDownloadFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tbReunioesAtaDownloadFocusGained

    }//GEN-LAST:event_tbReunioesAtaDownloadFocusGained

    private void tbReunioesAtaDownloadMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbReunioesAtaDownloadMouseClicked

    }//GEN-LAST:event_tbReunioesAtaDownloadMouseClicked

    private void tbReunioesAtaDownloadMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbReunioesAtaDownloadMouseReleased
        //taAta.setText(tbReunioesAtaDownload.getValueAt(tbReunioesAtaDownload.getSelectedRow(), 1).toString());
    }//GEN-LAST:event_tbReunioesAtaDownloadMouseReleased

    private void btnDownloadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDownloadActionPerformed
        
        if(tbReunioesAtaDownload.getSelectedRow() != -1){
            ConexaoSQLite connection = new ConexaoSQLite();
            ReuniaoDao rd = new ReuniaoDao(connection);
            Reuniao r = rd.gerarAtaDownload(tbReunioesAtaDownload.getValueAt(tbReunioesAtaDownload.getSelectedRow(), 0).toString());
            GeradorTxt grT = new GeradorTxt();
                try {
                    grT.gerarTxt(r);
                } catch (IOException ex) {
                    Logger.getLogger(TelaDownloadAta.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
    }//GEN-LAST:event_btnDownloadActionPerformed
    
    public void alimentarTabela() {

        DefaultTableModel tbAtaD = (DefaultTableModel) tbReunioesAtaDownload.getModel();
        tbAtaD.setNumRows(0);
        ConexaoSQLite connection = new ConexaoSQLite();
        ReuniaoDao rd = new ReuniaoDao(connection);

        for (Reuniao r : rd.listarTodasReunioes()) {
            
            System.out.println(r);
            
            tbAtaD.addRow(new Object[]{
                r.getId(),
                r.getDescricao(),
                r.getDataReuniao(),
                r.getHorarioInicio(),
                r.getHorarioFim(),
                r.getProprietario(),
                r.getLocal()
                
            });

        }

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDownload;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbReunioesAtaDownload;
    // End of variables declaration//GEN-END:variables
}
