/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import connection.ConexaoSQLite;
import dao.SalaDao;
import javax.swing.JOptionPane;
import model.Sala;

/**
 *
 * @author Paulo
 */
public class TelaCadastroSala extends javax.swing.JInternalFrame {

    /**
     * Creates new form TelaCadastroSala
     */
    public TelaCadastroSala() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        tfNomeSala = new javax.swing.JTextField();
        btnCadastrarSala = new javax.swing.JButton();

        setBackground(new java.awt.Color(230, 240, 240));
        setClosable(true);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Nome da Sala:");

        btnCadastrarSala.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnCadastrarSala.setText("Cadastrar");
        btnCadastrarSala.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastrarSalaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(85, 85, 85)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(tfNomeSala, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(84, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnCadastrarSala, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(156, 156, 156))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(92, 92, 92)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfNomeSala, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(40, 40, 40)
                .addComponent(btnCadastrarSala, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(99, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCadastrarSalaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastrarSalaActionPerformed
       
        ConexaoSQLite cSQL = new ConexaoSQLite();
        SalaDao sDao = new SalaDao(cSQL);
        int aux = 0; 
        for (Sala s : sDao.listarTodasSalas()) {
            System.out.println(s.getNome());
            if(tfNomeSala.getText().equalsIgnoreCase(s.getNome())){
                aux++;
            }
        }
        if(aux == 0){
            Sala s = new Sala();
            s.setNome(tfNomeSala.getText());
            cSQL.conectar();
            sDao.inserirSala(s);
        }else{
            JOptionPane.showMessageDialog(null, "Sala já existe");
        }
        
        
    }//GEN-LAST:event_btnCadastrarSalaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCadastrarSala;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField tfNomeSala;
    // End of variables declaration//GEN-END:variables
}
