/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import connection.ConexaoSQLite;
import dao.GestorRecursosDao;
import dao.ReuniaoDao;
import javax.swing.table.DefaultTableModel;
import model.Reuniao;

/**
 *
 * @author Paulo
 */
public class TelaReunioesConf extends javax.swing.JInternalFrame {

    /**
     * Creates new form TelaReunioesConf
     */
    public TelaReunioesConf() {
        initComponents();
        alimentarTabela();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tbReunioesConf = new javax.swing.JTable();

        setClosable(true);
        setResizable(true);

        tbReunioesConf.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "id", "Descrição", "Data", "Hora Inicio", "Hora Fim", "Proprietario", "Sala"
            }
        ));
        jScrollPane1.setViewportView(tbReunioesConf);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 657, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 637, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 449, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void alimentarTabela() {

        DefaultTableModel tbRc = (DefaultTableModel) tbReunioesConf.getModel();
        tbRc.setNumRows(0);
        ConexaoSQLite connection = new ConexaoSQLite();
        ReuniaoDao rd = new ReuniaoDao(connection);

        for (Reuniao r : rd.listarTodasReunioes()) {
            
            System.out.println(r);
            
            tbRc.addRow(new Object[]{
                r.getId(),
                r.getDescricao(),
                r.getDataReuniao(),
                r.getHorarioInicio(),
                r.getHorarioFim(),
                r.getProprietario(),
                r.getLocal()
                
            });

        }

    }
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbReunioesConf;
    // End of variables declaration//GEN-END:variables
}
